version: 2.0
jobs:
  checkout:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Cache
          keys:
            - pnpm-20200925b-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-20200925b-
      - run:
          name: Install Dependencies
          command: npx pnpm@5 install
      - save_cache:
          name: Save pnpm Cache
          key: pnpm-20200925b-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - /home/circleci/.pnpm-store/v3
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - ./*
            - node_modules

  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    environment:
      - LOGGER_LEVEL: silly
      - NODE_ENV: test
      - PORT: 3000
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Tests
          command: npx pnpm@5 run test

  publish:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    environment:
      - NODE_ENV: production
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Publish NPM Package
          command: ./node_modules/.bin/publish
      - run:
          name: Publish Changelog
          command: ./node_modules/.bin/push-changelog-update || true

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - publish:
          requires:
            - checkout
            - test
          filters:
            branches:
              only: master
